// Visual tour: screenshots of every major screen (test/out/tour-*.png)
import { launch, startServer } from './lib.mjs';
import fs from 'fs';
fs.mkdirSync('test/out', { recursive: true });
const srv = process.env.URL ? { url: process.env.URL, stop() {} } : await startServer();
const { browser, page, errors } = await launch();
const shot = async (n, wait = 600) => { await page.waitForTimeout(wait); await page.screenshot({ path: `test/out/tour-${n}.png` }); };
const ev = (fn, arg) => page.evaluate(fn, arg);
const closeAll = () => ev(() => { document.querySelectorAll('.modal-bg').forEach((m) => m.remove()); document.querySelectorAll('.mg').forEach((m) => m.querySelector('.mg-head .btn')?.click()); });
try {
  await page.goto(srv.url + '?autostart');
  await page.waitForFunction(() => window.__bb && window.__bb.clock, null, { timeout: 90000 });
  await shot('01-creator', 2500);
  await ev(() => document.querySelector('.panel-head .btn.mint').click());
  await shot('02-welcome', 900);
  for (let i = 0; i < 3; i++) await ev(() => document.querySelector('.dialog .btn')?.click());
  await ev(() => { const g = window.__bb; g.state.player.coins = 20000; g.state.player.xp = 9000; });
  await ev(() => window.__bb.pets.openShop()); await shot('03-petshop');
  await closeAll();
  await ev(() => { const g = window.__bb; g.pets.giveEgg('starter'); for (let i = 0; i < 3; i++) { g.state.needs.push({ id: 'hungry' }); g.pets.complete('hungry'); } });
  await page.waitForTimeout(2500);
  await ev(() => document.querySelector('.modal-bg .btn.mint')?.click());
  await ev(() => { const g = window.__bb; g.state.needs.push({ id: 'bored', t: 0 }); g.openPets(); });
  await shot('04-pets');
  await closeAll();
  await ev(() => { window.__bb.jobs.startJob('bakery'); }); await shot('05-bakery', 900);
  await ev(() => { document.querySelectorAll('.choice')[0].click(); document.querySelectorAll('.choice')[0].click(); document.querySelectorAll('.choice')[0].click(); });
  await shot('05b-bakery-built', 400);
  await closeAll(); await page.waitForTimeout(300);
  await ev(() => { window.__bb.jobs.startJob('florist'); }); await shot('06-florist', 900);
  await closeAll(); await page.waitForTimeout(300);
  await ev(() => { window.__bb.jobs.startJob('fishing'); }); await shot('07-fishing', 700);
  await closeAll(); await page.waitForTimeout(300);
  await ev(() => window.__bb.jobs.seedPicker(0)); await shot('08-seeds');
  await closeAll();
  await ev(() => window.__bb.openMap()); await shot('09-map');
  await closeAll();
  await ev(() => window.__bb.openSettings()); await shot('10-settings');
  await closeAll();
  await ev(() => { const g = window.__bb; g.world.interactables.find((i) => i.label === 'Sparkle Style').onUse(); }); await shot('11-boutique', 1200);
  await closeAll();
  await ev(() => window.__bb.vehicles.openShop()); await shot('12-rides', 1500);
  await closeAll();
  await ev(() => window.__bb.openBag()); await shot('13-bag');
  await closeAll();
  await ev(() => window.__bb.openQuests()); await shot('14-tasks');
  await closeAll();
  await ev(() => { const g = window.__bb; g.state.owned.vehicles.push('car'); g.state.owned.vehicleActive = 'car'; g.player.teleport(-10, undefined, 24, Math.PI / 2); g.vehicles.mount('car'); g.rig.yaw = -0.6; g.rig.pitch = 0.35; g.rig.dist = 9; g.sky.setTime(0.6); });
  await shot('15-car', 1200);
  await ev(() => { const g = window.__bb; g.vehicles.dismount(); g.player.teleport(2, undefined, 6); g.sky.setTime(0.95); g.rig.yaw = 0; g.rig.pitch = 0.25; });
  await shot('16-night', 1200);
  await ev(() => { const g = window.__bb; g.sky.setTime(0.45); const w = g.systems.find((s) => s.startRain); w.startRain(); w.rain = 1; });
  await shot('17-rain', 1500);
  await ev(() => { const g = window.__bb; const w = g.systems.find((s) => s.startRain); w.stopRain(); w.timer = 60; w.rbAlpha = 1; w.rain = 0; g.rig.yaw = Math.PI; });
  await shot('18-rainbow', 1500);
  await ev(() => { const g = window.__bb; g.state.unlocks.sky = true; g.vehicles.balloonUse(true); });
  await page.waitForTimeout(3500); await shot('19-balloon', 10);
  await page.waitForTimeout(4500); await shot('20-sky', 800);
} finally {
  console.log('errors:', errors.length ? errors.slice(0, 10).join('\n') : 'none');
  await browser.close();
  srv.stop();
}
